/** Turn the committed source SVGs into one generated module.
 *
 * The source files are Lucide's, unmodified, one per committed id. This strips
 * each down to the marks inside it and writes them into a single TypeScript
 * module, so a component names an icon by id and never holds a `<path>`.
 *
 * Generated, never hand-edited: `icons.spec.ts` regenerates and diffs.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, '..', 'src', 'lib', 'icons', 'svg');
const OUT_TS = resolve(here, '..', 'src', 'lib', 'icons', 'generated.ts');
const OUT_MANIFEST = resolve(here, '..', '..', 'frontend', 'src', 'lib', 'icons', 'manifest.json');

/** Everything between the opening and closing `<svg>` tag, whitespace collapsed.
 *
 * Lucide files carry the geometry as siblings, and the attributes that matter -
 * the 24-unit box, `currentColor`, the stroke width and the joins - are the
 * same on every one of them. `Icon.svelte` states them once rather than
 * repeating them 29 times.
 */
function marks(svg) {
	const open = svg.indexOf('>', svg.indexOf('<svg'));
	const close = svg.lastIndexOf('</svg>');
	return svg
		.slice(open + 1, close)
		.replace(/\s+/g, ' ')
		.replace(/>\s+</g, '><')
		.trim();
}

const files = readdirSync(SOURCE).filter((name) => name.endsWith('.svg'));

if (files.length === 0) {
	console.error('build-icons: no source SVGs under src/lib/icons/svg');
	process.exit(1);
}

// Sort on the id, not the filename: '-' sorts before '.', so topic-ai-roi.svg
// comes before topic-ai.svg while the ids go the other way. The contract
// requires sorted ids so a diff shows an addition rather than a reorder.
const entries = files
	.map((name) => ({
		id: name.replace(/\.svg$/, ''),
		marks: marks(readFileSync(join(SOURCE, name), 'utf8'))
	}))
	.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

const ts = `// Generated by scripts/build-icons.mjs from src/lib/icons/svg/*.svg.
// Do not edit. Add a source SVG and rebuild.
//
// Source: Lucide (https://lucide.dev), ISC licence - see PROVENANCE.md.

export const ICONS = {
${entries.map((e) => `\t'${e.id}': '${e.marks.replace(/'/g, "\\'")}'`).join(',\n')}
} as const;

export type IconId = keyof typeof ICONS;

export const ICON_IDS = Object.keys(ICONS) as IconId[];
`;

mkdirSync(dirname(OUT_TS), { recursive: true });
writeFileSync(OUT_TS, ts, 'utf8');

const manifest = {
	version: '2026-08-29',
	source: 'lucide',
	licence: 'ISC',
	icons: entries.map((e) => e.id)
};
writeFileSync(OUT_MANIFEST, JSON.stringify(manifest, null, 2) + '\n', 'utf8');

const bytes = entries.reduce((sum, e) => sum + e.marks.length, 0);
console.log(`build-icons: ${entries.length} icons, ${bytes} B of marks`);
