import { expect, test } from '@playwright/test';
import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICON_IDS, ICONS, type IconId } from '../src/lib/icons/generated';
import { iconsConfig } from '../src/lib/server/config';
import ts from 'typescript';

/**
 * A missing icon renders nothing at all.
 *
 * The generated id map keeps component types narrow. The page check confirms
 * that rendered topic marks use their container's colour.
 */

const FRONTEND = join(dirname(fileURLToPath(import.meta.url)), '..');
const ICON_DIRECTORY = join(FRONTEND, 'src', 'lib', 'icons');
const SVG_DIRECTORY = join(ICON_DIRECTORY, 'svg');
const ICON_BYTE_BUDGET = 40 * 1024;

function manifestIcons(): string[] {
	const manifest = JSON.parse(readFileSync(join(ICON_DIRECTORY, 'manifest.json'), 'utf8')) as {
		icons: string[];
	};
	return manifest.icons;
}

function sourceMarks(svg: string): string {
	const open = svg.indexOf('>', svg.indexOf('<svg'));
	const close = svg.lastIndexOf('</svg>');
	return svg
		.slice(open + 1, close)
		.replace(/\s+/g, ' ')
		.replace(/>\s+</g, '><')
		.trim();
}

function generatedFromManifest(): string {
	const entries = manifestIcons()
		.map((id) => ({
			id,
			marks: sourceMarks(readFileSync(join(SVG_DIRECTORY, `${id}.svg`), 'utf8'))
		}))
		.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
	return `// Generated by scripts/build-icons.mjs from the icon manifest's named SVGs.
// Do not edit. Add a source SVG to manifest.json and rebuild.
//
// Source: Lucide (https://lucide.dev), ISC licence - see PROVENANCE.md.

export const ICONS = {
${entries.map((entry) => `\t'${entry.id}': '${entry.marks.replace(/'/g, "\\'")}'`).join(',\n')}
} as const;

export type IconId = keyof typeof ICONS;

export const ICON_IDS = Object.keys(ICONS) as IconId[];
`;
}

function iconComponentSource(): string {
	return readFileSync(join(ICON_DIRECTORY, 'Icon.svelte'), 'utf8');
}

function invalidIconIdDiagnostics(): readonly ts.Diagnostic[] {
	const directory = mkdtempSync(join(tmpdir(), 'idhazh-icon-contract-'));
	const fixture = readFileSync(join(FRONTEND, 'tests', 'fixtures', 'icons', 'invalid-id.ts.txt'), 'utf8');
	const module = join(ICON_DIRECTORY, 'generated.ts').replaceAll('\\', '/');
	const options: ts.CompilerOptions = {
		module: ts.ModuleKind.ESNext,
		moduleResolution: ts.ModuleResolutionKind.Bundler,
		noEmit: true,
		skipLibCheck: true,
		strict: true,
		target: ts.ScriptTarget.ES2022,
		allowImportingTsExtensions: true,
		types: []
	};
	try {
		const file = join(directory, 'invalid-id.ts');
		writeFileSync(file, fixture.replace('"__ICON_TYPES__"', JSON.stringify(module)));
		return ts.getPreEmitDiagnostics(ts.createProgram([file], options));
	} finally {
		rmSync(directory, { recursive: true, force: true });
	}
}

test.describe('the icon set', () => {
	test('the generated icon map follows the named manifest list', () => {
		const icons = manifestIcons();
		expect(ICON_IDS).toEqual(icons);
		expect(Object.keys(ICONS)).toEqual(icons);
	});

	test('the generated id list matches the icon map', () => {
		const id: IconId = 'band-high';
		expect(ICON_IDS).toContain(id);
		expect(Object.keys(ICONS).sort()).toEqual([...ICON_IDS].sort());
	});

	test('the named SVG set stays inside its byte budget', () => {
		const bytes = manifestIcons().reduce(
			(sum, id) => sum + statSync(join(SVG_DIRECTORY, `${id}.svg`)).size,
			0
		);
		expect(bytes).toBeLessThanOrEqual(ICON_BYTE_BUDGET);
	});

	test('generated.ts is fresh against the manifest-named SVGs', () => {
		expect(readFileSync(join(ICON_DIRECTORY, 'generated.ts'), 'utf8')).toBe(
			generatedFromManifest()
		);
	});

	test('every size keeps the configured line width in screen pixels', async ({ page }) => {
		const source = iconComponentSource();
		expect(source).toContain('const strokeWidth = $derived((__ICON_STROKE_PX__ * 24) / size);');
		expect(source).toContain('stroke-width={strokeWidth}');
		const strokePx = iconsConfig().stroke_px;
		expect(strokePx).toBe(1.5);
		const sizes = [13, 14, 16, 20];
		const html = ICON_IDS.flatMap((id) =>
			sizes.map((size) => {
				const strokeUnits = (strokePx * 24) / size;
				return `<svg data-icon="${id}" data-size="${size}" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${strokeUnits}" stroke-linecap="round" stroke-linejoin="round">${ICONS[id]}</svg>`;
			})
		).join('');
		await page.setContent(html);
		const strokes = await page.locator('svg[data-icon]').evaluateAll((nodes) =>
			nodes.map((node) => {
				const svg = node as SVGSVGElement;
				const scale = svg.getScreenCTM()?.a ?? Number.NaN;
				return {
					id: svg.dataset.icon,
					size: Number(svg.dataset.size),
					screenStroke: Number(svg.getAttribute('stroke-width')) * scale
				};
			})
		);
		expect(strokes).toHaveLength(ICON_IDS.length * sizes.length);
		for (const stroke of strokes) {
			expect(stroke.screenStroke, `${stroke.id} at ${stroke.size} px`).toBeCloseTo(strokePx, 5);
		}
	});

	test('an id outside the named set is a type error', () => {
		const diagnostics = invalidIconIdDiagnostics();
		const errors = diagnostics.map((diagnostic) => ({
			code: diagnostic.code,
			message: ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n')
		}));
		expect(errors).toHaveLength(1);
		expect(errors[0].code).toBe(2322);
		expect(errors[0].message).toContain('__not-a-named-icon__');
	});
});

test.describe('icons on the page', () => {
	test('a topic pill carries its mark, in both themes', async ({ page }) => {
		await page.goto('/');
		const marks = await page.evaluate(() => {
			const pills = [...document.querySelectorAll('[data-topic-row] a')];
			return pills.map((p) => ({
				text: (p.textContent ?? '').trim().slice(0, 24),
				hasIcon: p.querySelector('svg.icon') !== null
			}));
		});
		expect(marks.length).toBeGreaterThan(1);
		// "All N" is not a topic and gets no mark; every named vertical does.
		expect(marks.slice(1).every((m) => m.hasIcon)).toBe(true);
	});

	test('a mark takes its colour from the thing it sits in', async ({ page }) => {
		await page.goto('/');
		const colours = await page.evaluate(async () => {
			const read = () => {
				const icon = document.querySelector('[data-band] svg.icon');
				return icon === null ? null : getComputedStyle(icon).color;
			};
			const dark = (document.documentElement.setAttribute('data-theme', 'dark'), read());
			await new Promise((done) => setTimeout(done, 250));
			document.documentElement.setAttribute('data-theme', 'light');
			await new Promise((done) => setTimeout(done, 250));
			return { dark, light: read() };
		});
		expect(colours.dark).not.toBeNull();
		expect(colours.light).not.toBe(colours.dark);
	});
});
