import { expect, test } from '@playwright/test';
import { readFileSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICON_IDS, ICONS, type IconId } from '../src/lib/icons/generated';
import ts from 'typescript';

/**
 * A missing icon renders nothing at all.
 *
 * The generated id map keeps component types narrow. The page check confirms
 * that rendered topic marks use their container's colour.
 */

const FRONTEND = join(dirname(fileURLToPath(import.meta.url)), '..');
const ICON_DIRECTORY = join(FRONTEND, 'src', 'lib', 'icons');
const SVG_DIRECTORY = join(ICON_DIRECTORY, 'svg');
const ICON_BYTE_BUDGET = 40 * 1024;

function manifestIcons(): string[] {
	const manifest = JSON.parse(readFileSync(join(ICON_DIRECTORY, 'manifest.json'), 'utf8')) as {
		icons: string[];
	};
	return manifest.icons;
}

function sourceMarks(svg: string): string {
	const open = svg.indexOf('>', svg.indexOf('<svg'));
	const close = svg.lastIndexOf('</svg>');
	return svg
		.slice(open + 1, close)
		.replace(/\s+/g, ' ')
		.replace(/>\s+</g, '><')
		.trim();
}

function generatedFromManifest(): string {
	const entries = manifestIcons()
		.map((id) => ({
			id,
			marks: sourceMarks(readFileSync(join(SVG_DIRECTORY, `${id}.svg`), 'utf8'))
		}))
		.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
	return `// Generated by scripts/build-icons.mjs from the icon manifest's named SVGs.
// Do not edit. Add a source SVG to manifest.json and rebuild.
//
// Source: Lucide (https://lucide.dev), ISC licence - see PROVENANCE.md.

export const ICONS = {
${entries.map((entry) => `\t'${entry.id}': '${entry.marks.replace(/'/g, "\\'")}'`).join(',\n')}
} as const;

export type IconId = keyof typeof ICONS;

export const ICON_IDS = Object.keys(ICONS) as IconId[];
`;
}

function invalidIconIdDiagnostics(): readonly ts.Diagnostic[] {
	const virtualFile = join(ICON_DIRECTORY, '__icon_type_contract__.ts');
	const source = [
		"import type { IconId } from './generated';",
		"const valid: IconId = 'band-high';",
		"const invalid: IconId = '__not-a-named-icon__';",
		'void valid;',
		'void invalid;'
	].join('\n');
	const options: ts.CompilerOptions = {
		module: ts.ModuleKind.ESNext,
		moduleResolution: ts.ModuleResolutionKind.Bundler,
		noEmit: true,
		skipLibCheck: true,
		strict: true,
		target: ts.ScriptTarget.ES2022
	};
	const host = ts.createCompilerHost(options);
	const getSourceFile = host.getSourceFile.bind(host);
	host.getSourceFile = (fileName, languageVersion, onError, shouldCreateNewSourceFile) =>
		fileName === virtualFile
			? ts.createSourceFile(fileName, source, languageVersion, true)
			: getSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile);
	const fileExists = host.fileExists.bind(host);
	host.fileExists = (fileName) => fileName === virtualFile || fileExists(fileName);
	const readFile = host.readFile.bind(host);
	host.readFile = (fileName) => (fileName === virtualFile ? source : readFile(fileName));
	return ts.getPreEmitDiagnostics(ts.createProgram([virtualFile], options, host));
}

test.describe('the icon set', () => {
	test('the generated icon map follows the named manifest list', () => {
		const icons = manifestIcons();
		expect(ICON_IDS).toEqual(icons);
		expect(Object.keys(ICONS)).toEqual(icons);
	});

	test('the generated id list matches the icon map', () => {
		const id: IconId = 'band-high';
		expect(ICON_IDS).toContain(id);
		expect(Object.keys(ICONS).sort()).toEqual([...ICON_IDS].sort());
	});

	test('the named SVG set stays inside its byte budget', () => {
		const bytes = manifestIcons().reduce(
			(sum, id) => sum + statSync(join(SVG_DIRECTORY, `${id}.svg`)).size,
			0
		);
		expect(bytes).toBeLessThanOrEqual(ICON_BYTE_BUDGET);
	});

	test('generated.ts is fresh against the manifest-named SVGs', () => {
		expect(readFileSync(join(ICON_DIRECTORY, 'generated.ts'), 'utf8')).toBe(
			generatedFromManifest()
		);
	});

	test('an id outside the named set is a type error', () => {
		const diagnostics = invalidIconIdDiagnostics();
		expect(diagnostics.some((diagnostic) => diagnostic.code === 2322)).toBe(true);
	});
});

test.describe('icons on the page', () => {
	test('a topic pill carries its mark, in both themes', async ({ page }) => {
		await page.goto('/');
		const marks = await page.evaluate(() => {
			const pills = [...document.querySelectorAll('[data-topic-row] a')];
			return pills.map((p) => ({
				text: (p.textContent ?? '').trim().slice(0, 24),
				hasIcon: p.querySelector('svg.icon') !== null
			}));
		});
		expect(marks.length).toBeGreaterThan(1);
		// "All N" is not a topic and gets no mark; every named vertical does.
		expect(marks.slice(1).every((m) => m.hasIcon)).toBe(true);
	});

	test('a mark takes its colour from the thing it sits in', async ({ page }) => {
		await page.goto('/');
		const colours = await page.evaluate(async () => {
			const read = () => {
				const icon = document.querySelector('[data-band] svg.icon');
				return icon === null ? null : getComputedStyle(icon).color;
			};
			const dark = (document.documentElement.setAttribute('data-theme', 'dark'), read());
			await new Promise((done) => setTimeout(done, 250));
			document.documentElement.setAttribute('data-theme', 'light');
			await new Promise((done) => setTimeout(done, 250));
			return { dark, light: read() };
		});
		expect(colours.dark).not.toBeNull();
		expect(colours.light).not.toBe(colours.dark);
	});
});
