//! Real filesystem checks for whole-file replacement and immutable publication.

#[path = "../src/fs/atomic.rs"]
mod atomic;

use atomic::{publish_immutable, write_atomic_bytes};
use std::{
    fs, io,
    path::{Path, PathBuf},
    process::Command,
    sync::{
        Arc, Barrier,
        atomic::{AtomicBool, AtomicU64, Ordering},
        mpsc,
    },
    thread,
    time::Duration,
};

static NEXT_DIRECTORY: AtomicU64 = AtomicU64::new(0);

struct TestDirectory(PathBuf);

impl TestDirectory {
    fn new(name: &str) -> Self {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("..")
            .join("var")
            .join("d11-atomic-tests");
        fs::create_dir_all(&root).unwrap();
        for _ in 0..128 {
            let nonce = NEXT_DIRECTORY.fetch_add(1, Ordering::Relaxed);
            let path = root.join(format!("{name}-{}-{nonce}", std::process::id()));
            match fs::create_dir(&path) {
                Ok(()) => return Self(path),
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(error) => panic!("cannot create generated test directory: {error}"),
            }
        }
        panic!("generated test-directory names exhausted");
    }

    fn path(&self) -> &Path {
        &self.0
    }

    fn join(&self, name: &str) -> PathBuf {
        self.0.join(name)
    }

    fn assert_entries(&self, expected: &[&str]) {
        // This directory was generated by this test, never a committed archive.
        let mut names: Vec<_> = fs::read_dir(&self.0)
            .unwrap()
            .map(|entry| entry.unwrap().file_name().into_string().unwrap())
            .collect();
        names.sort();
        let mut expected = expected.to_vec();
        expected.sort();
        assert_eq!(names, expected);
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        fs::remove_dir_all(&self.0).unwrap();
    }
}

#[test]
fn replaces_binary_bytes_creates_parents_and_accepts_empty_files() {
    let directory = TestDirectory::new("replacement");
    let path = directory.join("nested").join("data.bin");
    write_atomic_bytes(&path, b"\0\r\n\xfforiginal").unwrap();
    assert_eq!(fs::read(&path).unwrap(), b"\0\r\n\xfforiginal");
    write_atomic_bytes(&path, b"\xff\0replacement\r\n").unwrap();
    assert_eq!(fs::read(&path).unwrap(), b"\xff\0replacement\r\n");
    write_atomic_bytes(&path, b"").unwrap();
    assert!(fs::read(&path).unwrap().is_empty());
    assert_eq!(fs::read_dir(path.parent().unwrap()).unwrap().count(), 1);
}

#[test]
fn replacement_observer_sees_only_complete_old_or_new_files() {
    let directory = TestDirectory::new("replacement-observer");
    let path = directory.join("data.bin");
    let old = Arc::new(vec![0x35; 256 * 1024]);
    let new = Arc::new(vec![0xca; 384 * 1024]);
    write_atomic_bytes(&path, &old).unwrap();
    let stop = Arc::new(AtomicBool::new(false));
    let (ready, started) = mpsc::channel();
    let (saw_new, observed_new) = mpsc::channel();
    let observer = {
        let path = path.clone();
        let old = old.clone();
        let new = new.clone();
        let stop = stop.clone();
        thread::spawn(move || {
            assert_eq!(fs::read(&path).unwrap(), *old);
            ready.send(()).unwrap();
            let mut observations = 0;
            let mut reported_new = false;
            while !stop.load(Ordering::Acquire) {
                let bytes = fs::read(&path).unwrap();
                assert!(bytes == *old || bytes == *new, "partial replacement");
                if bytes == *new && !reported_new {
                    saw_new.send(()).unwrap();
                    reported_new = true;
                }
                observations += 1;
                thread::yield_now();
            }
            let bytes = fs::read(&path).unwrap();
            assert!(bytes == *old || bytes == *new);
            observations
        })
    };
    started.recv().unwrap();
    for iteration in 0..64 {
        let bytes = if iteration % 2 == 0 { &new } else { &old };
        write_atomic_bytes(&path, bytes).unwrap();
    }
    write_atomic_bytes(&path, &new).unwrap();
    observed_new.recv_timeout(Duration::from_secs(10)).unwrap();
    stop.store(true, Ordering::Release);
    assert!(observer.join().unwrap() > 0);
    assert_eq!(fs::read(&path).unwrap(), *new);
    directory.assert_entries(&["data.bin"]);
}

#[test]
fn real_rename_failure_preserves_destination_directory_and_siblings() {
    let directory = TestDirectory::new("rename-failure");
    let path = directory.join("destination");
    fs::create_dir(&path).unwrap();
    fs::write(path.join("old.bin"), b"old file must survive").unwrap();
    fs::write(directory.join("sibling.bin"), b"sibling").unwrap();
    fs::write(
        directory.join(".idhazh-atomic-foreign.tmp"),
        b"foreign temp",
    )
    .unwrap();
    assert!(write_atomic_bytes(&path, b"must not replace a directory").is_err());
    assert!(path.is_dir());
    assert_eq!(
        fs::read(path.join("old.bin")).unwrap(),
        b"old file must survive"
    );
    assert_eq!(fs::read(directory.join("sibling.bin")).unwrap(), b"sibling");
    assert_eq!(
        fs::read(directory.join(".idhazh-atomic-foreign.tmp")).unwrap(),
        b"foreign temp"
    );
    directory.assert_entries(&[".idhazh-atomic-foreign.tmp", "destination", "sibling.bin"]);
}

#[cfg(windows)]
#[test]
fn denied_replacement_preserves_the_existing_file() {
    use std::os::windows::fs::OpenOptionsExt;
    let directory = TestDirectory::new("locked-file");
    let path = directory.join("old.bin");
    fs::write(&path, b"original").unwrap();
    // Permit reads/writes, but deny delete-sharing so rename really fails.
    let held = fs::OpenOptions::new()
        .read(true)
        .share_mode(0x1 | 0x2)
        .open(&path)
        .unwrap();
    assert!(write_atomic_bytes(&path, b"replacement").is_err());
    assert_eq!(fs::read(&path).unwrap(), b"original");
    publish_immutable(&path, b"original").unwrap();
    directory.assert_entries(&["old.bin"]);
    drop(held);
    write_atomic_bytes(&path, b"replacement").unwrap();
    assert_eq!(fs::read(&path).unwrap(), b"replacement");
}

#[test]
fn immutable_publication_is_binary_exact_and_identical_retries_succeed() {
    let directory = TestDirectory::new("immutable-identical");
    let path = directory.join("nested").join("uuid.bin");
    let bytes = b"\0\xff\r\nimmutable";
    publish_immutable(&path, bytes).unwrap();
    publish_immutable(&path, bytes).unwrap();
    assert_eq!(fs::read(&path).unwrap(), bytes);
    assert_eq!(fs::read_dir(path.parent().unwrap()).unwrap().count(), 1);
    let empty = directory.join("empty.bin");
    publish_immutable(&empty, b"").unwrap();
    publish_immutable(&empty, b"").unwrap();
    assert!(fs::read(&empty).unwrap().is_empty());
}

#[test]
fn immutable_collision_reports_conflict_and_preserves_original_and_siblings() {
    let directory = TestDirectory::new("immutable-conflict");
    let path = directory.join("uuid.bin");
    publish_immutable(&path, b"original").unwrap();
    fs::write(directory.join("sibling.bin"), b"sibling").unwrap();
    fs::write(directory.join(".idhazh-atomic-foreign.tmp"), b"foreign").unwrap();
    for conflicting in [b"changed!".as_slice(), b"different length".as_slice()] {
        let error = publish_immutable(&path, conflicting).unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::AlreadyExists);
        let diagnostic = error.to_string();
        assert!(diagnostic.contains("conflict"));
        assert!(diagnostic.contains("uuid.bin"));
        assert_eq!(fs::read(&path).unwrap(), b"original");
    }
    assert_eq!(fs::read(directory.join("sibling.bin")).unwrap(), b"sibling");
    assert_eq!(
        fs::read(directory.join(".idhazh-atomic-foreign.tmp")).unwrap(),
        b"foreign"
    );
    directory.assert_entries(&[".idhazh-atomic-foreign.tmp", "sibling.bin", "uuid.bin"]);
}

#[test]
fn immutable_destination_directory_is_a_conflict_not_a_replacement() {
    let directory = TestDirectory::new("immutable-directory");
    let path = directory.join("uuid.bin");
    fs::create_dir(&path).unwrap();
    fs::write(path.join("old.bin"), b"old").unwrap();
    let error = publish_immutable(&path, b"new").unwrap_err();
    assert_eq!(error.kind(), io::ErrorKind::AlreadyExists);
    assert!(error.to_string().contains("conflict"));
    assert_eq!(fs::read(path.join("old.bin")).unwrap(), b"old");
    directory.assert_entries(&["uuid.bin"]);
}

#[test]
fn concurrent_identical_immutable_writers_all_succeed_without_temp_leaks() {
    let directory = TestDirectory::new("immutable-same-writers");
    let path = directory.join("uuid.bin");
    let bytes = Arc::new(vec![0x52; 256 * 1024]);
    let barrier = Arc::new(Barrier::new(8));
    let writers: Vec<_> = (0..8)
        .map(|_| {
            let path = path.clone();
            let bytes = bytes.clone();
            let barrier = barrier.clone();
            thread::spawn(move || {
                barrier.wait();
                publish_immutable(&path, &bytes)
            })
        })
        .collect();
    for writer in writers {
        writer.join().unwrap().unwrap();
    }
    assert_eq!(fs::read(&path).unwrap(), *bytes);
    directory.assert_entries(&["uuid.bin"]);
}

#[test]
fn concurrent_conflicting_writers_have_one_whole_winner_and_diagnosed_losers() {
    let directory = TestDirectory::new("immutable-competing-writers");
    let path = directory.join("uuid.bin");
    let candidates: Arc<Vec<Vec<u8>>> = Arc::new(
        (0..8)
            .map(|index| vec![index as u8; (128 + index) * 1024])
            .collect(),
    );
    let barrier = Arc::new(Barrier::new(candidates.len() + 1));
    let stop = Arc::new(AtomicBool::new(false));
    let observer = {
        let path = path.clone();
        let candidates = candidates.clone();
        let barrier = barrier.clone();
        let stop = stop.clone();
        thread::spawn(move || {
            barrier.wait();
            let mut winner = None;
            loop {
                match fs::read(&path) {
                    Ok(bytes) => {
                        assert!(candidates.contains(&bytes), "partial immutable publication");
                        if let Some(previous) = &winner {
                            assert_eq!(&bytes, previous, "immutable destination changed");
                        } else {
                            winner = Some(bytes);
                        }
                    }
                    Err(error) if error.kind() == io::ErrorKind::NotFound => {
                        assert!(winner.is_none(), "immutable destination disappeared");
                    }
                    Err(error) => panic!("observer failed: {error}"),
                }
                if stop.load(Ordering::Acquire)
                    && let Some(bytes) = winner.take()
                {
                    return bytes;
                }
                thread::yield_now();
            }
        })
    };
    let writers: Vec<_> = (0..candidates.len())
        .map(|index| {
            let path = path.clone();
            let candidates = candidates.clone();
            let barrier = barrier.clone();
            thread::spawn(move || {
                barrier.wait();
                (index, publish_immutable(&path, &candidates[index]))
            })
        })
        .collect();
    let mut winners = Vec::new();
    for writer in writers {
        let (index, result) = writer.join().unwrap();
        match result {
            Ok(()) => winners.push(index),
            Err(error) => {
                assert_eq!(error.kind(), io::ErrorKind::AlreadyExists);
                assert!(error.to_string().contains("conflict"));
            }
        }
    }
    stop.store(true, Ordering::Release);
    let observed = observer.join().unwrap();
    assert_eq!(winners.len(), 1);
    assert_eq!(observed, candidates[winners[0]]);
    assert_eq!(fs::read(&path).unwrap(), observed);
    directory.assert_entries(&["uuid.bin"]);
}

#[test]
fn temp_collisions_are_bounded_and_never_delete_foreign_files() {
    const CHILD_DIRECTORY: &str = "IDHAZH_ATOMIC_COLLISION_TEST_DIRECTORY";
    if let Some(directory) = std::env::var_os(CHILD_DIRECTORY) {
        // A separate test process gives this module a fresh temporary nonce.
        let directory = PathBuf::from(directory);
        let temporary =
            |nonce| directory.join(format!(".idhazh-atomic-{}-{nonce}.tmp", std::process::id()));
        fs::write(temporary(0), b"foreign").unwrap();
        let path = directory.join("data.bin");
        write_atomic_bytes(&path, b"old").unwrap();
        assert_eq!(fs::read(temporary(0)).unwrap(), b"foreign");
        assert!(!temporary(1).exists());
        for nonce in 2..130 {
            fs::write(temporary(nonce), b"foreign").unwrap();
        }
        let error = write_atomic_bytes(&path, b"new").unwrap_err();
        assert_eq!(error.kind(), io::ErrorKind::AlreadyExists);
        assert!(error.to_string().contains("128 name collisions"));
        assert_eq!(fs::read(&path).unwrap(), b"old");
        for nonce in std::iter::once(0).chain(2..130) {
            assert_eq!(fs::read(temporary(nonce)).unwrap(), b"foreign");
        }
        assert_eq!(fs::read_dir(&directory).unwrap().count(), 130);
        return;
    }
    let directory = TestDirectory::new("temp-collisions");
    let output = Command::new(std::env::current_exe().unwrap())
        .args([
            "--exact",
            "temp_collisions_are_bounded_and_never_delete_foreign_files",
            "--nocapture",
        ])
        .env(CHILD_DIRECTORY, directory.path())
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

#[cfg(any(unix, windows))]
#[test]
fn destination_symlinks_including_dangling_links_are_refused() {
    let directory = TestDirectory::new("symlinks");
    let target = directory.join("target.bin");
    let link = directory.join("link.bin");
    fs::write(&target, b"original").unwrap();
    #[cfg(unix)]
    let result = std::os::unix::fs::symlink(&target, &link);
    #[cfg(windows)]
    let result = std::os::windows::fs::symlink_file(&target, &link);
    if let Err(error) = result {
        #[cfg(windows)]
        if error.kind() == io::ErrorKind::PermissionDenied || error.raw_os_error() == Some(1314) {
            eprintln!("symlink test unavailable: Windows denied symlink creation: {error}");
            return;
        }
        panic!("cannot create real symlink: {error}");
    }
    for bytes in [b"original".as_slice(), b"different".as_slice()] {
        assert_eq!(
            write_atomic_bytes(&link, bytes).unwrap_err().kind(),
            io::ErrorKind::InvalidInput
        );
        assert_eq!(
            publish_immutable(&link, bytes).unwrap_err().kind(),
            io::ErrorKind::InvalidInput
        );
    }
    assert_eq!(fs::read(&target).unwrap(), b"original");
    fs::remove_file(&target).unwrap();
    assert_eq!(
        write_atomic_bytes(&link, b"new").unwrap_err().kind(),
        io::ErrorKind::InvalidInput
    );
    assert_eq!(
        publish_immutable(&link, b"new").unwrap_err().kind(),
        io::ErrorKind::InvalidInput
    );
    assert!(!target.exists());
    assert!(
        fs::symlink_metadata(&link)
            .unwrap()
            .file_type()
            .is_symlink()
    );
    directory.assert_entries(&["link.bin"]);
}
